apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-app-raw
  name: demo-app-raw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-raw
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app-raw
    spec:
      containers:
        - image: busybox
          name: demo
          command:
            - /bin/sleep
          args:
            - "10d"
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
status: {}