apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 360
  backoffLimit: 1
  template:
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          command:
            - /bin/sleep
          args:
            - '10d'
          resources:
            limits:
              cpu: 20m
              memory: 25M
            requests:
              cpu: 20m
              memory: 10M
          name: post-sync-two
      restartPolicy: OnFailure
