apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kust-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/rumstead/argocd-playground.git'
    path: manifests/kustomize/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true