apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-job-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/rumstead/argocd-playground.git'
    path: manifests/sync-hooks
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true