apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radius-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/rumstead/argocd-playground.git'
    path: radius/demo/chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
      prune: true