apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-release-ag-service
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: manifests/applicationsets/webhook-15427/cloud-release/ag-service/*.yaml
        repoURL: https://github.com/rumstead/argocd-playground.git
        revision: dev
  template:
    metadata:
      name: '{{acmeService.name}}'
    spec:
      destination:
        namespace: '{{acmeService.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: manifests/kustomize/
        repoURL: https://github.com/rumstead/argocd-playground.git
        targetRevision: '{{release.targetRevision}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true